#!/bin/bash
cd `dirname $0`
killall mongod && rm /data/db/mongod.lock
mongod > /dev/null &
disown
source skeleton crossover-social-media-site
tmux new-window -t $TMUX_SESSION \;\
     send-keys -t $TMUX_SESSION:4 'mongo crossover' C-m \;\
     attach
