#!/bin/bash
cd ~/K/cubictube
#kill -9 `ps aux | grep dynamodb-local | grep -v grep | awk '{print $2}'`
TMUX_SESSION='dev_cubictube'
tmux attach -t $TMUX_SESSION || tmux new-session -d -s $TMUX_SESSION -n 'vim' -c "$PWD" \;\
     new-window -n 'api' -c "$PWD/backend/api" \;\
     new-window -n 'web-app' -c "$PWD/web-app" \;\
     new-window \;\
     send-keys -t $TMUX_SESSION:0 'vim' C-m \;\
     send-keys -t $TMUX_SESSION:1 'npm start' C-m \;\
     send-keys -t $TMUX_SESSION:2 'npm start' C-m \;\
     send-keys -t $TMUX_SESSION:3 'dynamodb-local -sharedDb -dbPath /var/dynamodb' C-m \;\
     select-window -t "$TMUX_SESSION:0" \;\
     attach
