#!/bin/bash

if [ -z "$GRADLE_DEBUG_PORT" ] ; then
    GRADLE_DEBUG_PORT=`find_free_port.sh 5005 1`
fi

JAVA_OPTS="$JAVA_OPTS -Xdebug -Xnoagent -Dgrails.full.stacktrace=true -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=$GRADLE_DEBUG_PORT" gradle "$@"
