#!/bin/bash
cd `dirname $0`
killall mongod && rm /data/db/mongod.lock
mongod > /dev/null &
disown
source skeleton instablog
tmux new-window -t $TMUX_SESSION \;\
     send-keys -t $TMUX_SESSION:4 'mongo instablog' C-m \;\
     attach
