#!/bin/bash - 
if [ ! -z "$1" ] ; then
    #title "riskmatch $1"
    IP=`aws ec2 describe-instances --region ap-southeast-1 --profile rm | node -pe "[].concat.apply([], JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).Reservations.map(function(r) { return r.Instances; })).find(function(i) { return i.Tags.find(function(t) { return t.Value == 'abalchunas-dev-server'; }) != null }).PublicIpAddress"`
    (cat /etc/hosts | grep -v remote-dev-server-riskmatch; echo "$IP remote-dev-server-riskmatch") > /tmp/hosts.new && cat /tmp/hosts.new > /etc/hosts
    ssh ubuntu@$IP -i ~/.ssh/abalchunas-dev-server.pem -t "(cat /etc/hosts | grep -v remote-dev-server-riskmatch; echo '$IP remote-dev-server-riskmatch') > /tmp/hosts.new && cat /tmp/hosts.new > /etc/hosts; riskmatch"
else
    cd ~/K/risk
    TMUX_SESSION=`echo "dev_riskmatch@$HOSTNAME" | sed -e 's/\./_/g'`
    tmux attach -d -t $TMUX_SESSION || tmux new-session -d -s $TMUX_SESSION -n 'vim' -c "$PWD" \;\
         new-window -n 'frontend' -c "$PWD/frontend" \;\
         new-window -n 'spark' -c "$PWD/backend/spark" \;\
         new-window -n 'MS' -c "$PWD/backend/master-site" \;\
         new-window -n 'MW' -c "$PWD/backend/master-worker" \;\
         new-window -n 'BS' -c "$PWD/backend/broker-site" \;\
         new-window -n 'BW' -c "$PWD/backend/broker-worker" \;\
         new-window -n 'CS' -c "$PWD/backend/carrier-site" \;\
         new-window -n 'CW' -c "$PWD/backend/carrier-worker" \;\
         new-window -n 'MySQL' \;\
         new-window -n 'backend-v2' -c "$PWD/backend-v2" \;\
         send-keys -t $TMUX_SESSION:9 'mysql -u root' C-m \;\
         select-window -t "$TMUX_SESSION:0" \;\
         attach
fi
