#!/bin/bash

if [ -z "$SBT_DEBUG_PORT" ] ; then
    SBT_DEBUG_PORT=`find_free_port.sh 5005 1`
fi

SBT_OPTS="$SBT_OPTS -Xdebug -Xnoagent -Dgrails.full.stacktrace=true -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=$SBT_DEBUG_PORT" sbt "$@"
